In [1]:
import numpy as np

In [26]:
a = np.array([0, 1, 4, 6, 12])
b = np.array([-1, 1, 2, 5, 9, 12, 22])
print(np.searchsorted(a, b))
print(np.searchsorted(a, b, side='right'))
print(np.searchsorted(a, b) % 5)


[0 1 2 3 4 4 5]
[0 2 2 3 4 5 5]
[0 1 2 3 4 4 0]


In [22]:
b - a[np.searchsorted(a, b)]

IndexError: index 5 is out of bounds for axis 1 with size 5

In [23]:
b - a[np.searchsorted(a, b)-1]

array([-13,   1,   1,   1,   3,   6,  10])

In [30]:
np.minimum(abs(b - a[np.searchsorted(a, b) % len(a)]), abs(b - a[np.searchsorted(a, b)-1]))

array([ 1,  0,  1,  1,  3,  0, 10])

In [8]:
b - a[np.searchsorted(a, b, side='right')-1]

array([0, 1, 3])